### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Aditya94A** [dchrastil/ScrapedIn#14]

**Comment by dchrastil** [comment]
There is an updated version I have in a private repo that has been updated and improved functionality. I will release this soon

**Comment by cclauss** [comment]
flake8 testing of https://github.com/dchrastil/ScrapedIn on Python 3.9.0rc1+

flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
```
./ScrapedIn.py:84:11: E999 SyntaxError: invalid syntax
    print "[Info] %i Results Found" % data_total
          ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by TheTerminator2** [comment]
> There is an updated version I have in a private repo that has been updated and improved functionality. I will release this soon
> 
> 

Would be great I'm also on the look for something to work with LinkedIn.

**Comment by nilkamal-bahaji** [comment]
Any update on new version ? anything we could help with ?

**Comment by dchrastil** [comment]
This is resolved in the new version.
