### ISSUE TITLE
tweepy 4.14.0 requires requests 2.27.0

### ISSUE THREAD

**Issue by zaniityy** [dchrastil/ScrapedIn#24]
I've installed the latest "requests" and tried to update it, it says it's at the newest version.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tweepy 4.14.0 requires requests<3,>=2.27.0, but you have requests 2.20.0 which is incompatible.`

**Comment by dchrastil** [comment]
This is resolved in the new version.
