### ISSUE TITLE
No JSON returned

### ISSUE THREAD

**Issue by PeterMuellerT** [dchrastil/ScrapedIn#5]
The URL "https://www.linkedin.com/voyager/api/search/cluster?count=40&guides=List(v-%%3EPEOPLE,facetGeoRegion-%%3Ear%%3A0)&keywords=%s&origin=FACETED_SEARCH&q=guided&start=0" does not return a json object for me.

So decoding fails.. :(

Here have the example.
[error.txt](https://github.com/dchrastil/ScrapedIn/files/1871145/error.txt)

**Comment by AdamTheAnalyst** [comment]
Try changing the JSESSION ID in the ScrapedIn.py file to one from a valid cookie for your account.

Worked for me.

**Comment by dchrastil** [comment]
This is resolved in the new version.
