### ISSUE TITLE
No module named Thready

### ISSUE THREAD

**Issue by tacticthreat** [dchrastil/ScrapedIn#6]
When I try to launch the python script I get the error: 

root@kali:~/ScrapedIn# python ScrapedIn.py 
Traceback (most recent call last):
  File "ScrapedIn.py", line 20, in <module>
    from thready import threaded
ImportError: No module named thready

I've ran pip install thready but even though the requirement is supposedly satisfied, the error persists.

**Comment by zeire** [comment]
easy_install thready

**Comment by Silversgit** [comment]
pip install thready
